
package com.pg.ws.client.handler.universaltime;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UniversalTimeService", targetNamespace = "http://universaltime.handler.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UniversalTimeService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentTime", targetNamespace = "http://universaltime.handler.ws.pg.com/", className = "com.pg.ws.client.handler.universaltime.GetCurrentTime")
    @ResponseWrapper(localName = "getCurrentTimeResponse", targetNamespace = "http://universaltime.handler.ws.pg.com/", className = "com.pg.ws.client.handler.universaltime.GetCurrentTimeResponse")
    public String getCurrentTime(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
