
package com.pg.ws.binding.client.doc.literal.bare;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocLiteralBareServiceSEI", targetNamespace = "http://bare.literal.doc.binding.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/wsimport/DocLiteralBare/DocLiteralBareServiceSEI.wsdl")
public class DocLiteralBareServiceSEI
    extends Service
{

    private final static URL DOCLITERALBARESERVICESEI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.binding.client.doc.literal.bare.DocLiteralBareServiceSEI.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.binding.client.doc.literal.bare.DocLiteralBareServiceSEI.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/wsimport/DocLiteralBare/DocLiteralBareServiceSEI.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/wsimport/DocLiteralBare/DocLiteralBareServiceSEI.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCLITERALBARESERVICESEI_WSDL_LOCATION = url;
    }

    public DocLiteralBareServiceSEI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocLiteralBareServiceSEI() {
        super(DOCLITERALBARESERVICESEI_WSDL_LOCATION, new QName("http://bare.literal.doc.binding.ws.pg.com/", "DocLiteralBareServiceSEI"));
    }

    /**
     * 
     * @return
     *     returns DocLiteralBareService
     */
    @WebEndpoint(name = "DocLiteralBareServiceImplPort")
    public DocLiteralBareService getDocLiteralBareServiceImplPort() {
        return super.getPort(new QName("http://bare.literal.doc.binding.ws.pg.com/", "DocLiteralBareServiceImplPort"), DocLiteralBareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocLiteralBareService
     */
    @WebEndpoint(name = "DocLiteralBareServiceImplPort")
    public DocLiteralBareService getDocLiteralBareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bare.literal.doc.binding.ws.pg.com/", "DocLiteralBareServiceImplPort"), DocLiteralBareService.class, features);
    }

}
