
package com.pg.ws.client.stub.math;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MapTableServiceImplService", targetNamespace = "http://math.simpleserver.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/MapTableServiceImplService.wsdl")
public class MapTableServiceImplService
    extends Service
{

    private final static URL MAPTABLESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.client.stub.math.MapTableServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.client.stub.math.MapTableServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/MapTableServiceImplService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/MapTableServiceImplService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MAPTABLESERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MapTableServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MapTableServiceImplService() {
        super(MAPTABLESERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://math.simpleserver.ws.pg.com/", "MapTableServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns MapTableService
     */
    @WebEndpoint(name = "MapTableServiceImplPort")
    public MapTableService getMapTableServiceImplPort() {
        return super.getPort(new QName("http://math.simpleserver.ws.pg.com/", "MapTableServiceImplPort"), MapTableService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MapTableService
     */
    @WebEndpoint(name = "MapTableServiceImplPort")
    public MapTableService getMapTableServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://math.simpleserver.ws.pg.com/", "MapTableServiceImplPort"), MapTableService.class, features);
    }

}
