
package com.pg.ws.soap.stub.math;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MapTableService", targetNamespace = "http://math.simpleserver.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MapTableService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSquare", targetNamespace = "http://math.simpleserver.ws.pg.com/", className = "com.pg.ws.soap.stub.math.GetSquare")
    @ResponseWrapper(localName = "getSquareResponse", targetNamespace = "http://math.simpleserver.ws.pg.com/", className = "com.pg.ws.soap.stub.math.GetSquareResponse")
    public String getSquare(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
