
package com.pg.ws.simpleclient.implsei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClassJustSEI", targetNamespace = "http://implsei.simpleserver.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClassJustSEI {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://implsei.simpleserver.ws.pg.com/", className = "com.pg.ws.simpleclient.implsei.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://implsei.simpleserver.ws.pg.com/", className = "com.pg.ws.simpleclient.implsei.SayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://implsei.simpleserver.ws.pg.com/", className = "com.pg.ws.simpleclient.implsei.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://implsei.simpleserver.ws.pg.com/", className = "com.pg.ws.simpleclient.implsei.SayByeResponse")
    public String sayBye();

}
