
package com.pg.ws.simpleclient.implsei;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ClassJustImplSEIService", targetNamespace = "http://implsei.simpleserver.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/ClassJustImplSEIService.wsdl")
public class ClassJustImplSEIService
    extends Service
{

    private final static URL CLASSJUSTIMPLSEISERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.simpleclient.implsei.ClassJustImplSEIService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.simpleclient.implsei.ClassJustImplSEIService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/ClassJustImplSEIService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/ClassJustImplSEIService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CLASSJUSTIMPLSEISERVICE_WSDL_LOCATION = url;
    }

    public ClassJustImplSEIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClassJustImplSEIService() {
        super(CLASSJUSTIMPLSEISERVICE_WSDL_LOCATION, new QName("http://implsei.simpleserver.ws.pg.com/", "ClassJustImplSEIService"));
    }

    /**
     * 
     * @return
     *     returns ClassJustSEI
     */
    @WebEndpoint(name = "ClassJustImplSEIPort")
    public ClassJustSEI getClassJustImplSEIPort() {
        return super.getPort(new QName("http://implsei.simpleserver.ws.pg.com/", "ClassJustImplSEIPort"), ClassJustSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassJustSEI
     */
    @WebEndpoint(name = "ClassJustImplSEIPort")
    public ClassJustSEI getClassJustImplSEIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implsei.simpleserver.ws.pg.com/", "ClassJustImplSEIPort"), ClassJustSEI.class, features);
    }

}
