
package com.pg.ws.client.binding.rpc.literal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RPCLiteralService", targetNamespace = "http://literal.rpc.binding.ws.pg.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RPCLiteralService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.pg.ws.client.binding.rpc.literal.ExchangeRateBO
     */
    @WebMethod
    @WebResult(partName = "return")
    public ExchangeRateBO getExchangeRate(
        @WebParam(name = "arg0", partName = "arg0")
        ExchangeRateRequestBO arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
