
package com.pg.ws.binding.client.doc.literal.wrap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocLiteralWrapServiceSEI", targetNamespace = "http://wrap.literal.doc.binding.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/wsimport/DocLiteralWrap/DocLiteralWrapServiceSEI.wsdl")
public class DocLiteralWrapServiceSEI
    extends Service
{

    private final static URL DOCLITERALWRAPSERVICESEI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.binding.client.doc.literal.wrap.DocLiteralWrapServiceSEI.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.binding.client.doc.literal.wrap.DocLiteralWrapServiceSEI.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/wsimport/DocLiteralWrap/DocLiteralWrapServiceSEI.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspace/X_WS_SOAP_Java/wsdl/wsimport/DocLiteralWrap/DocLiteralWrapServiceSEI.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCLITERALWRAPSERVICESEI_WSDL_LOCATION = url;
    }

    public DocLiteralWrapServiceSEI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocLiteralWrapServiceSEI() {
        super(DOCLITERALWRAPSERVICESEI_WSDL_LOCATION, new QName("http://wrap.literal.doc.binding.ws.pg.com/", "DocLiteralWrapServiceSEI"));
    }

    /**
     * 
     * @return
     *     returns DocLiteralWrapService
     */
    @WebEndpoint(name = "DocLiteralWrapServiceImplPort")
    public DocLiteralWrapService getDocLiteralWrapServiceImplPort() {
        return super.getPort(new QName("http://wrap.literal.doc.binding.ws.pg.com/", "DocLiteralWrapServiceImplPort"), DocLiteralWrapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocLiteralWrapService
     */
    @WebEndpoint(name = "DocLiteralWrapServiceImplPort")
    public DocLiteralWrapService getDocLiteralWrapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wrap.literal.doc.binding.ws.pg.com/", "DocLiteralWrapServiceImplPort"), DocLiteralWrapService.class, features);
    }

}
